micronaut:
  application:
    name: pix
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    username: 'postgres'
    password: 'password'

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

itau:
  contas:
    url: 'http://localhost:9091'

bc:
  pix:
    url: 'http://localhost:8082'